import Foundation

enum SharedStrings {
    static let tabHome = LocalizationUtility.translate("tab_home", fallback: "Home")
    static let tabSettings = LocalizationUtility.translate("tab_settings", fallback: "Settings")
    static let settingsTitle = LocalizationUtility.translate("settings_title", fallback: "Settings")
    static let settingsLanguageTitle = LocalizationUtility.translate("settings_language_title", fallback: "Language")
    static let settingsLanguageEnglish = LocalizationUtility.translate("settings_language_english", fallback: "English")
    static let settingsLanguageArabic = LocalizationUtility.translate("settings_language_arabic", fallback: "Arabic")
    static let settingsClearAllTasks = LocalizationUtility.translate("settings_clear_all_tasks", fallback: "Clear all tasks")
    static let settingsClearAllTasksConfirmationTitle = LocalizationUtility.translate("settings_clear_all_tasks_confirmation_title", fallback: "Are you sure?")
    static let settingsClearAllTasksConfirmationMessage = LocalizationUtility.translate("settings_clear_all_tasks_confirmation_message", fallback: "This will remove all tasks permanently.")
    static let settingsClearAllTasksConfirm = LocalizationUtility.translate("settings_clear_all_tasks_confirm", fallback: "Delete")
    static let settingsClearAllTasksCancel = LocalizationUtility.translate("settings_clear_all_tasks_cancel", fallback: "Cancel")
    static let inboxTitle = LocalizationUtility.translate("inbox_title", fallback: "Inbox")
    static let todayHeader = LocalizationUtility.translate("today_header", fallback: "TODAY")
    static let noTasksTitle = LocalizationUtility.translate("no_tasks_title", fallback: "No tasks yet")
    static let noTasksMessage = LocalizationUtility.translate("no_tasks_message", fallback: "Tap + to add your first task")
    static let newTaskTitle = LocalizationUtility.translate("new_task_title", fallback: "New Task")
    static let editTaskTitle = LocalizationUtility.translate("edit_task_title", fallback: "Edit Task")
    static let cancelButton = LocalizationUtility.translate("cancel_button", fallback: "Cancel")
    static let saveButton = LocalizationUtility.translate("save_button", fallback: "Save")
    static let deleteTaskButton = LocalizationUtility.translate("delete_task_button", fallback: "Delete Task")
    static let taskTitlePlaceholder = LocalizationUtility.translate("task_title_placeholder", fallback: "Task Title")
    static let notesPlaceholder = LocalizationUtility.translate("notes_placeholder", fallback: "Add some details...")
    static let setDueDateToggle = LocalizationUtility.translate("set_due_date_toggle", fallback: "Set Due Date")
    static let whatNeedsToBeDone = LocalizationUtility.translate("what_needs_to_be_done", fallback: "What needs to be done?")
    static let notesLabel = LocalizationUtility.translate("notes_label", fallback: "Notes")
}
